name: CI/CD Pipeline with Testing and Scanning

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  call-whitebox:
    uses: ./.github/workflows/whitebox.yml
  
  call-graybox:
    uses: ./.github/workflows/graybox.yml

  call-blackbox:
    uses: ./.github/workflows/blackbox.yml