name: CI/CD Pipeline with Testing and Scanning

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        cd webApp
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests (pytest)
      run: |
        cd webApp
        pytest

    - name: Build Docker image
      run: |
        cd webApp
        docker build -t flask-webapp .

    - name: Tag Docker image for Docker Hub
      run: |
        docker tag flask-webapp ${{ secrets.DOCKER_USERNAME }}/flask-webapp:latest

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/flask-webapp:latest

  Static-Code-Analysis:
    runs-on: ubuntu-latest
    needs: build-test  

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Semgrep and Bandit
      run: |
        pip install semgrep bandit

    - name: Run Semgrep
      run: |
        semgrep --config p/default webApp || true

    - name: Run Bandit (Python security linter)
      run: |
        bandit -r webApp -lll --exit-zero

  post-deployment-pentesting:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Docker dependencies and build image
      run: |
        cd webApp
        docker build -t flask-webapp .

    - name: Create Docker network
      run: docker network create zapnet

    - name: Run Flask app container
      run: |
        docker run --network zapnet -d --name pentest-target flask-webapp
        sleep 10

    - name: Confirm Flask app is reachable inside zapnet
      run: |
        docker run --rm --network zapnet curlimages/curl curl -s http://pentest-target:5000 || (echo "App not reachable!" && exit 1)

    # ✅ Run ffuf inside Docker in zapnet
    - name: Install SecLists Wordlist
      run: |
        mkdir -p ${{ github.workspace }}/wordlists
        curl -sSL https://raw.githubusercontent.com/danielmiessler/SecLists/refs/heads/master/Discovery/Web-Content/directory-list-2.3-small.txt -o ${{ github.workspace }}/wordlists/fuzzlist.txt

    - name: Run directory fuzzing with ffuf (Docker)
      run: |
        docker run --rm --network zapnet \
        -v ${{ github.workspace }}/wordlists:/wordlists \
        -v ${{ github.workspace }}/scan-reports:/ffuf/output \
        secsi/ffuf \
        -u http://pentest-target:5000/FUZZ \
        -w /wordlists/fuzzlist.txt \
        -mc 200,302 \
        -s \
        -o /ffuf/output/ffuf.json \
        -of json || true

    - name: Show ffuf results
      run: |
        echo "===== FFUF RESULTS ====="
        cat scan-reports/ffuf.json || echo "⚠️ No ffuf output found"

    - name: Extract paths from ffuf output for ZAP
      run: |
        sudo chmod -R 777 scan-reports
        jq -r '.results[].input | "http://pentest-target:5000" + .FUZZ' scan-reports/ffuf.json > scan-reports/zap-urls.txt
        cat scan-reports/zap-urls.txt

    # ✅ Run Nuclei in Docker in zapnet

    - name: Prepare Nuclei targets from FFUF results
      run: |
        sudo chmod -R 777 scan-reports
        jq -r '.results[].input | "http://pentest-target:5000" + .FUZZ' scan-reports/ffuf.json > scan-reports/ffuf-urls.txt
        cat scan-reports/ffuf-urls.txt


    - name: Run nuclei scan (in Docker)
      run: |
        mkdir -p scan-reports
        docker run --rm --network zapnet \
          -v ${{ github.workspace }}/scan-reports:/output \
          projectdiscovery/nuclei:latest \
          -l /output/ffuf-urls.txt \
          -severity critical,high,medium,low,info \
          -o /output/nuclei.txt || true

    - name: Show nuclei results
      run: |
        echo "===== NUCLEI RESULTS ====="
        cat scan-reports/nuclei.txt || echo "⚠️ No nuclei output found"

    - name: Pull OWASP ZAP Docker image
      run: docker pull ghcr.io/zaproxy/zaproxy:stable

    - name: Prepare ZAP report directory
      run: |
        mkdir -p zap-reports
        chmod 777 zap-reports

    # ✅ Run ZAP with URLs discovered from ffuf
    # --- ZAP FULL SCAN ---
    - name: Run ZAP Full Scan (Crawl + Attack)
      run: |
        docker run --rm --network zapnet \
          -v ${{ github.workspace }}/zap-reports:/zap/wrk \
          -t ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py \
          -t http://pentest-target:5000 \
          -J zap-full-report.json -r zap-full-report.html || true

    - name: Print ZAP FULL SCAN Findings in CLI table
      run: |
        echo "=== ZAP API FINDINGS ==="
        jq -r '.site[0].alerts[] | [.riskdesc, .alert, .url] | @tsv' zap-reports/zap-full-report.json | column -t -s $'\t'

    # --- ZAP API SCAN ---
    - name: Run ZAP API Scan (Active + Passive)
      run: |
        docker run --rm --network zapnet \
          -v ${{ github.workspace }}/zap-reports:/zap/wrk \
          -t ghcr.io/zaproxy/zaproxy:stable zap-api-scan.py \
          -t http://pentest-target:5000/openapi.json \
          -f openapi \
          -d \
          -a \
          -J zap-api-report.json -r zap-api-report.html || true

    - name: Print ZAP API Findings in CLI table
      run: |
        echo "=== ZAP API FINDINGS ==="
        jq -r '.site[0].alerts[] | [.riskdesc, .alert, .url] | @tsv' zap-reports/zap-api-report.json | column -t -s $'\t'

    - name: Stop and remove app container
      if: always()
      run: |
        docker stop pentest-target
        docker rm pentest-target

    - name: Remove Docker network
      if: always()
      run: docker network rm zapnet
