name: CI/CD Pipeline with Testing and Scanning

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        cd webApp
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests (pytest)
      run: |
        cd webApp
        pytest

    - name: Build Docker image
      run: |
        cd webApp
        docker build -t flask-webapp .

    - name: Tag Docker image for Docker Hub
      run: |
        docker tag flask-webapp ${{ secrets.DOCKER_USERNAME }}/flask-webapp:latest

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/flask-webapp:latest

  scan:
    runs-on: ubuntu-latest
    needs: build-test  

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Semgrep and Bandit
      run: |
        pip install semgrep bandit

    - name: Run Semgrep
      run: |
        semgrep --config p/default webApp || true

    - name: Run Bandit (Python security linter)
      run: |
        bandit -r webApp -lll --exit-zero

  post-deployment-pentesting:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Docker dependencies and build image
      run: |
        cd webApp
        docker build -t flask-webapp .

    - name: Create Docker network
      run: docker network create zapnet

    - name: Run Flask app container locally
      run: |
        docker run --network zapnet -d --name pentest-target flask-webapp


    - name: Install ffuf
      run: |
        sudo apt-get update && sudo apt-get install -y ffuf

    - name: Install SecLists Wordlist
      run: |
        mkdir -p wordlists
        curl -sSL https://raw.githubusercontent.com/danielmiessler/SecLists/master/Discovery/Web-Content/directories-small.txt -o wordlists/fuzzlist.txt

    - name: Run directory fuzzing with ffuf
      run: |
        mkdir -p scan-reports
        ffuf -u http://pentest-target:5000/FUZZ \
          -w wordlists/fuzzlist.txt \
          -mc 200,302 \
          -o scan-reports/ffuf.json -of json || true

    - name: Show ffuf fuzzing results
      run: |
        echo "===== FFUF FUZZING RESULTS ====="
        cat scan-reports/ffuf.json || echo "⚠️ No ffuf output found"

    - name: Print discovered paths
      run: cat scan-reports/ffuf.json

    - name: Prepare URL list for OWASP ZAP
      run: |
        jq -r '.results[].input | "http://pentest-target:5000" + .FUZZ' scan-reports/ffuf.json > scan-reports/zap-urls.txt
        cat scan-reports/zap-urls.txt

    - name: Install Nuclei (latest release)
      run: |
        sudo apt-get update && sudo apt-get install -y jq
        URL=$(curl -s https://api.github.com/repos/projectdiscovery/nuclei/releases/latest | jq -r '.assets[] | select(.name | test("linux_amd64.zip$")) | .browser_download_url')
        wget "$URL" -O nuclei.zip
        unzip -o nuclei.zip
        chmod +x nuclei
        sudo mv nuclei /usr/local/bin/
        nuclei -version

    - name: Run Nuclei scan
      run: |
        mkdir -p scan-reports
        nuclei -u http://pentest-target:5000 -severity critical,high,medium -o scan-reports/nuclei.txt || true

    - name: Pull OWASP ZAP Docker image
      run: docker pull ghcr.io/zaproxy/zaproxy:stable

    - name: Prepare ZAP report directory
      run: |
        mkdir -p zap-reports
        chmod 777 zap-reports

    - name: Run OWASP ZAP with custom URLs (Active Scan)
      run: |
        docker run --network zapnet \
          -v $(pwd)/zap-reports:/zap/wrk/:rw \
          -v $(pwd)/scan-reports/zap-urls.txt:/zap/wrk/urls.txt \
          ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
          -r zap-fuzz-report.html -I -z "-config urls.file=/zap/wrk/urls.txt" || true

    - name: Show ZAP Fuzz Report
      run: |
        echo "===== ZAP FUZZ SCAN REPORT ====="
        cat zap-reports/zap-fuzz-report.html || echo "Report not found"

    - name: Stop and clean up Docker container
      if: always()
      run: |
        docker stop pentest-target
        docker rm pentest-target

    - name: Remove Docker network
      if: always()
      run: docker network rm zapnet
