name: CI/CD Pipeline with Testing and Scanning

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        cd webApp
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests (pytest)
      run: |
        cd webApp
        pytest

    - name: Build Docker image
      run: |
        cd webApp
        docker build -t flask-webapp .

    - name: Tag Docker image for Docker Hub
      run: |
        docker tag flask-webapp ${{ secrets.DOCKER_USERNAME }}/flask-webapp:latest

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/flask-webapp:latest

  scan:
    runs-on: ubuntu-latest
    needs: build-test  

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Semgrep and Bandit
      run: |
        pip install semgrep bandit

    - name: Run Semgrep
      run: |
        semgrep --config p/default webApp || true

    - name: Run Bandit (Python security linter)
      run: |
        bandit -r webApp -lll --exit-zero

  post-deployment-pentesting:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Docker dependencies and build image
      run: |
        cd webApp
        docker build -t flask-webapp .

    - name: Run Flask app container locally
      run: |
        docker run -d -p 5000:5000 --name pentest-target flask-webapp
        sleep 10  # give app time to start

    - name: Install Nuclei (latest release)
      run: |
        URL=$(curl -s https://api.github.com/repos/projectdiscovery/nuclei/releases/latest | grep "browser_download_url.*linux_amd64.zip" | cut -d '"' -f 4)
        wget "$URL" -O nuclei.zip
        unzip -o nuclei.zip
        chmod +x nuclei
        sudo mv nuclei /usr/local/bin/
        nuclei -version

    - name: Run Nuclei scan
      run: |
        mkdir -p scan-reports
        nuclei -u http://localhost:5000 -severity critical,high,medium -o scan-reports/nuclei.txt || true

    - name: Pull OWASP ZAP Docker image explicitly
      run: |
        docker pull owasp/zap2docker-stable || sleep 10 && docker pull owasp/zap2docker-stable

        - name: Run OWASP ZAP Full Scan (Docker)
          run: |
            docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-full-scan.py \
              -t http://host.docker.internal:5000 -r zap-full-report.html || true

    - name: Run OWASP ZAP Full Scan (Docker)
      run: |
        docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-full-scan.py \
          -t http://host.docker.internal:5000 -r zap-full-report.html || true
    
    - name: Parse OWASP ZAP Full Scan Report
      run: |
        if grep -iE 'Medium|High' zap-full-report.html; then
          echo "❌ ZAP Full Scan found Medium or High vulnerabilities"
          exit 1
        else
          echo "✅ ZAP Full Scan found no Medium or High issues"
        fi

    - name: Stop and clean up Docker container
      if: always()
      run: |
        docker stop pentest-target
        docker rm pentest-target
